# dotnet-api-repo/k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-api-deployment
  namespace: dotnet-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-api
  template:
    metadata:
      labels:
        app: dotnet-api
    spec:
      containers:
      - name: dotnet-api
        # IMPORTANT: Replace with your GHCR image path
        # Use a placeholder that CI/ArgoCD can update, or use a stable tag like :main
        image: ghcr.io/ucanbaklava-cicd/api # Placeholder or stable tag
        ports:
        - containerPort: 8080 # Must match ASPNETCORE_URLS and Dockerfile EXPOSE
        # Add environment variables, secrets, configmaps if needed
        # env:
        # - name: MY_SETTING
        #   value: "some_value"

        readinessProbe:
          httpGet:
            path: /api/health  # Your health check endpoint
            port: 8080         # The container port
          initialDelaySeconds: 15 # Wait 15s after container starts before first probe
          periodSeconds: 10     # Probe every 10s
          timeoutSeconds: 5      # Wait max 5s for response
          failureThreshold: 3    # Mark as Unready after 3 consecutive failures
          successThreshold: 1    # Mark as Ready after 1 successful probe (following failure)

        livenessProbe:
          httpGet:
            path: /api/health  # Your health check endpoint
            port: 8080         # The container port
          initialDelaySeconds: 30 # Wait longer before starting liveness checks
          periodSeconds: 20     # Probe less frequently than readiness
          timeoutSeconds: 5
          failureThreshold: 3    # Restart container after 3 consecutive failures