# dotnet-api-repo/.github/workflows/ci.yaml
name: Build and Push API Image

on:
  push:
    branches: [ "main" ] # Trigger on push to main branch
  workflow_dispatch: # Allow manual trigger

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} # Use the actual repository name

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Needed to push to GHCR

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }} # Use built-in token

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=sha # Tag with commit SHA (e.g., ghcr.io/owner/repo:sha-abcdef1)
          type=raw,value=latest # Also tag with :latest

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./K8S.API # Build from API project directory
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: ./K8S.API/Dockerfile # Specify Dockerfile location
